<a href="https://colab.research.google.com/github/kmeiyalagan/hashicat-gcp/blob/master/Pandas_Class_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('file2.csv')

In [ ]:
data

      Unnamed: 0    Dev_Ref
0           1043  013.094.G
1           1044  013.094.G
2           1045  013.094.C
3           1046  013.094.C
4           1047  013.094.B
...          ...        ...
4459      248545  097.050.E
4460      248546  097.050.F
4461      248547  097.050.F
4462      248548  097.050.G
4463      248549  097.050.G

[4464 rows x 2 columns]

In [ ]:
data.Dev_Ref.unique()

array(['013.094.G', '013.094.C', '013.094.B', '013.094.A', '013.094.F',
       '013.094.E', '041.050.G', '041.050.C', '041.050.B', '041.050.A',
       '041.050.F', '041.050.E', '041.138.A', '041.138.B', '041.138.C',
       '041.138.E', '041.138.F', '041.138.G', '055.116.A', '055.116.B',
       '055.116.C', '055.116.E', '055.116.F', '055.116.G', '055.149.E',
       '055.061.E', '055.072.A', '055.072.B', '055.072.C', '055.072.E',
       '055.072.F', '055.072.G', '069.160.A', '069.160.B', '069.160.C',
       '069.160.E', '069.160.F', '069.160.G', '069.028.A', '069.028.B',
       '069.028.C', '069.028.E', '069.028.F', '069.028.G', '069.094.A',
       '069.094.B', '069.094.C', '069.094.E', '069.094.F', '069.094.G',
       '111.149.E', '111.061.E', '125.094.A', '125.094.B', '125.094.C',
       '125.094.E', '125.094.F', '125.094.G', '083.105.E', '083.116.A',
       '083.116.B', '083.116.C', '083.116.E', '083.116.F', '083.116.G',
       '083.072.A', '083.072.B', '083.072.C', '083.072.E', '083.072.F',
       '083.072.G', '097.138.A', '097.138.B', '097.138.C', '097.138.E',
       '097.138.F', '097.138.G', '097.050.A', '097.050.B', '097.050.C',
       '097.050.E', '097.050.F', '097.050.G'], dtype=object)

In [ ]:
data['Dev_Ref'].nunique()

83

In [ ]:
# Groups based on user input
a = input('Please enter the Dev_Ref :',)
b = data.groupby('Dev_Ref').get_group(a)
b.reset_index()

Please enter the Dev_Ref :013.094.G

    index  Unnamed: 0    Dev_Ref
0       0        1043  013.094.G
1       1        1044  013.094.G
2     196        9251  013.094.G
3     197        9252  013.094.G
4     382       17612  013.094.G
5     383       17613  013.094.G
6     568       25973  013.094.G
7     569       25974  013.094.G
8     744       43795  013.094.G
9     745       43796  013.094.G
10    940       52003  013.094.G
11    941       52004  013.094.G
12   1126       60364  013.094.G
13   1127       60365  013.094.G
14   1312       68725  013.094.G
15   1313       68726  013.094.G
16   1488       86547  013.094.G
17   1489       86548  013.094.G
18   1684       94895  013.094.G
19   1685       94896  013.094.G
20   1870      103256  013.094.G
21   1871      103257  013.094.G
22   2056      111617  013.094.G
23   2057      111618  013.094.G
24   2232      129376  013.094.G
25   2233      129377  013.094.G
26   2428      137560  013.094.G
27   2429      137561  013.094.G
28   2614      145752  013.094.G
29   2615      145753  013.094.G
30   2800      153944  013.094.G
31   2801      153945  013.094.G
32   2976      171384  013.094.G
33   2977      171385  013.094.G
34   3172      179568  013.094.G
35   3173      179569  013.094.G
36   3358      187760  013.094.G
37   3359      187761  013.094.G
38   3544      195952  013.094.G
39   3545      195953  013.094.G
40   3720      213392  013.094.G
41   3721      213393  013.094.G
42   3916      221576  013.094.G
43   3917      221577  013.094.G
44   4102      229768  013.094.G
45   4103      229769  013.094.G
46   4288      237960  013.094.G
47   4289      237961  013.094.G

In [ ]:
# All groups list
for i in data.Dev_Ref.unique():
    print(i)
    print(pd.DataFrame(data.groupby('Dev_Ref').get_group(i)))
    print('\n\n\n\n\n')

013.094.G
      Unnamed: 0    Dev_Ref
0           1043  013.094.G
1           1044  013.094.G
196         9251  013.094.G
197         9252  013.094.G
382        17612  013.094.G
383        17613  013.094.G
568        25973  013.094.G
569        25974  013.094.G
744        43795  013.094.G
745        43796  013.094.G
940        52003  013.094.G
941        52004  013.094.G
1126       60364  013.094.G
1127       60365  013.094.G
1312       68725  013.094.G
1313       68726  013.094.G
1488       86547  013.094.G
1489       86548  013.094.G
1684       94895  013.094.G
1685       94896  013.094.G
1870      103256  013.094.G
1871      103257  013.094.G
2056      111617  013.094.G
2057      111618  013.094.G
2232      129376  013.094.G
2233      129377  013.094.G
2428      137560  013.094.G
2429      137561  013.094.G
2614      145752  013.094.G
2615      145753  013.094.G
2800      153944  013.094.G
2801      153945  013.094.G
2976      171384  013.094.G
2977      171385  013.094.G
3172      179568  013.094.G
3173      179569  013.094.G
3358      187760  013.094.G
3359      187761  013.094.G
3544      195952  013.094.G
3545      195953  013.094.G
3720      213392  013.094.G
3721      213393  013.094.G
3916      221576  013.094.G
3917      221577  013.094.G
4102      229768  013.094.G
4103      229769  013.094.G
4288      237960  013.094.G
4289      237961  013.094.G






013.094.C
      Unnamed: 0    Dev_Ref
2           1045  013.094.C
3           1046  013.094.C
190         9244  013.094.C
191         9245  013.094.C
376        17605  013.094.C
377        17606  013.094.C
562        25966  013.094.C
563        25967  013.094.C
746        43797  013.094.C
747        43798  013.094.C
934        51996  013.094.C
935        51997  013.094.C
1120       60357  013.094.C
1121       60358  013.094.C
1306       68718  013.094.C
1307       68719  013.094.C
1490       86549  013.094.C
1491       86550  013.094.C
1678       94888  013.094.C
1679       94889  013.094.C
1864      103249  013.094.C
1865      103250  013.094.C
2050      111610  013.094.C
2051      111611  013.094.C
2234      129378  013.094.C
2235      129379  013.094.C
2422      137554  013.094.C
2423      137555  013.094.C
2608      145746  013.094.C
2609      145747  013.094.C
2794      153938  013.094.C
2795      153939  013.094.C
2978      171386  013.094.C
2979      171387  013.094.C
3166      179562  013.094.C
3167      179563  013.094.C
3352      187754  013.094.C
3353      187755  013.094.C
3538      195946  013.094.C
3539      195947  013.094.C
3722      213394  013.094.C
3723      213395  013.094.C
3910      221570  013.094.C
3911      221571  013.094.C
4096      229762  013.094.C
4097      229763  013.094.C
4282      237954  013.094.C
4283      237955  013.094.C






013.094.B
      Unnamed: 0    Dev_Ref
4           1047  013.094.B
5           1048  013.094.B
188         9242  013.094.B
189         9243  013.094.B
374        17603  013.094.B
375        17604  013.094.B
560        25964  013.094.B
561        25965  013.094.B
748        43799  013.094.B
749        43800  013.094.B
932        51994  013.094.B
933        51995  013.094.B
1118       60355  013.094.B
1119       60356  013.094.B
1304       68716  013.094.B
1305       68717  013.094.B
1492       86551  013.094.B
1493       86552  013.094.B
1676       94886  013.094.B
1677       94887  013.094.B
1862      103247  013.094.B
1863      103248  013.094.B
2048      111608  013.094.B
2049      111609  013.094.B
2236      129380  013.094.B
2237      129381  013.094.B
2420      137552  013.094.B
2421      137553  013.094.B
2606      145744  013.094.B
2607      145745  013.094.B
2792      153936  013.094.B
2793      153937  013.094.B
2980      171388  013.094.B
2981      171389  013.094.B
3164      179560  013.094.B
3165      179561  013.094.B
3350      187752  013.094.B
3351      187753  013.094.B
3536      195944  013.094.B
3537      195945  013.094.B
3724      213396  013.094.B
3725      213397  013.094.B
3908      221568  013.094.B
3909      221569  013.094.B
4094      229760  013.094.B
4095      229761  013.094.B
4280      237952  013.094.B
4281      237953  013.094.B






013.094.A
      Unnamed: 0    Dev_Ref
6           1049  013.094.A
7           1050  013.094.A
186         9240  013.094.A
187         9241  013.094.A
372        17601  013.094.A
373        17602  013.094.A
558        25962  013.094.A
559        25963  013.094.A
750        43801  013.094.A
751        43802  013.094.A
930        51992  013.094.A
931        51993  013.094.A
1116       60353  013.094.A
1117       60354  013.094.A
1302       68714  013.094.A
1303       68715  013.094.A
1494       86553  013.094.A
1495       86554  013.094.A
1674       94884  013.094.A
1675       94885  013.094.A
1860      103245  013.094.A
1861      103246  013.094.A
2046      111606  013.094.A
2047      111607  013.094.A
2238      129382  013.094.A
2239      129383  013.094.A
2418      137550  013.094.A
2419      137551  013.094.A
2604      145742  013.094.A
2605      145743  013.094.A
2790      153934  013.094.A
2791      153935  013.094.A
2982      171390  013.094.A
2983      171391  013.094.A
3162      179558  013.094.A
3163      179559  013.094.A
3348      187750  013.094.A
3349      187751  013.094.A
3534      195942  013.094.A
3535      195943  013.094.A
3726      213398  013.094.A
3727      213399  013.094.A
3906      221566  013.094.A
3907      221567  013.094.A
4092      229758  013.094.A
4093      229759  013.094.A
4278      237950  013.094.A
4279      237951  013.094.A






013.094.F
      Unnamed: 0    Dev_Ref
8           1051  013.094.F
9           1052  013.094.F
194         9249  013.094.F
195         9250  013.094.F
380        17610  013.094.F
381        17611  013.094.F
566        25971  013.094.F
567        25972  013.094.F
752        43803  013.094.F
753        43804  013.094.F
938        52001  013.094.F
939        52002  013.094.F
1124       60362  013.094.F
1125       60363  013.094.F
1310       68723  013.094.F
1311       68724  013.094.F
1496       86555  013.094.F
1497       86556  013.094.F
1682       94893  013.094.F
1683       94894  013.094.F
1868      103254  013.094.F
1869      103255  013.094.F
2054      111615  013.094.F
2055      111616  013.094.F
2240      129384  013.094.F
2241      129385  013.094.F
2426      137558  013.094.F
2427      137559  013.094.F
2612      145750  013.094.F
2613      145751  013.094.F
2798      153942  013.094.F
2799      153943  013.094.F
2984      171392  013.094.F
2985      171393  013.094.F
3170      179566  013.094.F
3171      179567  013.094.F
3356      187758  013.094.F
3357      187759  013.094.F
3542      195950  013.094.F
3543      195951  013.094.F
3728      213400  013.094.F
3729      213401  013.094.F
3914      221574  013.094.F
3915      221575  013.094.F
4100      229766  013.094.F
4101      229767  013.094.F
4286      237958  013.094.F
4287      237959  013.094.F






013.094.E
      Unnamed: 0    Dev_Ref
10          1053  013.094.E
11          1054  013.094.E
192         9247  013.094.E
193         9248  013.094.E
378        17608  013.094.E
379        17609  013.094.E
564        25969  013.094.E
565        25970  013.094.E
754        43805  013.094.E
755        43806  013.094.E
936        51999  013.094.E
937        52000  013.094.E
1122       60360  013.094.E
1123       60361  013.094.E
1308       68721  013.094.E
1309       68722  013.094.E
1498       86557  013.094.E
1499       86558  013.094.E
1680       94891  013.094.E
1681       94892  013.094.E
1866      103252  013.094.E
1867      103253  013.094.E
2052      111613  013.094.E
2053      111614  013.094.E
2242      129386  013.094.E
2243      129387  013.094.E
2424      137556  013.094.E
2425      137557  013.094.E
2610      145748  013.094.E
2611      145749  013.094.E
2796      153940  013.094.E
2797      153941  013.094.E
2986      171394  013.094.E
2987      171395  013.094.E
3168      179564  013.094.E
3169      179565  013.094.E
3354      187756  013.094.E
3355      187757  013.094.E
3540      195948  013.094.E
3541      195949  013.094.E
3730      213402  013.094.E
3731      213403  013.094.E
3912      221572  013.094.E
3913      221573  013.094.E
4098      229764  013.094.E
4099      229765  013.094.E
4284      237956  013.094.E
4285      237957  013.094.E






041.050.G
      Unnamed: 0    Dev_Ref
12          1521  041.050.G
13          1522  041.050.G
220         9939  041.050.G
221         9940  041.050.G
406        18300  041.050.G
407        18301  041.050.G
592        26661  041.050.G
593        26662  041.050.G
756        44273  041.050.G
757        44274  041.050.G
964        52691  041.050.G
965        52692  041.050.G
1150       61052  041.050.G
1151       61053  041.050.G
1336       69413  041.050.G
1337       69414  041.050.G
1500       87025  041.050.G
1501       87026  041.050.G
1708       95583  041.050.G
1709       95584  041.050.G
1894      103944  041.050.G
1895      103945  041.050.G
2080      112305  041.050.G
2081      112306  041.050.G
2244      129841  041.050.G
2245      129842  041.050.G
2452      138229  041.050.G
2453      138230  041.050.G
2638      146421  041.050.G
2639      146422  041.050.G
2824      154613  041.050.G
2825      154614  041.050.G
2988      171849  041.050.G
2989      171850  041.050.G
3196      180237  041.050.G
3197      180238  041.050.G
3382      188429  041.050.G
3383      188430  041.050.G
3568      196621  041.050.G
3569      196622  041.050.G
3732      213857  041.050.G
3733      213858  041.050.G
3940      222245  041.050.G
3941      222246  041.050.G
4126      230437  041.050.G
4127      230438  041.050.G
4312      238629  041.050.G
4313      238630  041.050.G






041.050.C
      Unnamed: 0    Dev_Ref
14          1523  041.050.C
15          1524  041.050.C
214         9932  041.050.C
215         9933  041.050.C
400        18293  041.050.C
401        18294  041.050.C
586        26654  041.050.C
587        26655  041.050.C
758        44275  041.050.C
759        44276  041.050.C
958        52684  041.050.C
959        52685  041.050.C
1144       61045  041.050.C
1145       61046  041.050.C
1330       69406  041.050.C
1331       69407  041.050.C
1502       87027  041.050.C
1503       87028  041.050.C
1702       95576  041.050.C
1703       95577  041.050.C
1888      103937  041.050.C
1889      103938  041.050.C
2074      112298  041.050.C
2075      112299  041.050.C
2246      129843  041.050.C
2247      129844  041.050.C
2446      138223  041.050.C
2447      138224  041.050.C
2632      146415  041.050.C
2633      146416  041.050.C
2818      154607  041.050.C
2819      154608  041.050.C
2990      171851  041.050.C
2991      171852  041.050.C
3190      180231  041.050.C
3191      180232  041.050.C
3376      188423  041.050.C
3377      188424  041.050.C
3562      196615  041.050.C
3563      196616  041.050.C
3734      213859  041.050.C
3735      213860  041.050.C
3934      222239  041.050.C
3935      222240  041.050.C
4120      230431  041.050.C
4121      230432  041.050.C
4306      238623  041.050.C
4307      238624  041.050.C






041.050.B
      Unnamed: 0    Dev_Ref
16          1525  041.050.B
17          1526  041.050.B
212         9930  041.050.B
213         9931  041.050.B
398        18291  041.050.B
399        18292  041.050.B
584        26652  041.050.B
585        26653  041.050.B
760        44277  041.050.B
761        44278  041.050.B
956        52682  041.050.B
957        52683  041.050.B
1142       61043  041.050.B
1143       61044  041.050.B
1328       69404  041.050.B
1329       69405  041.050.B
1504       87029  041.050.B
1505       87030  041.050.B
1700       95574  041.050.B
1701       95575  041.050.B
1886      103935  041.050.B
1887      103936  041.050.B
2072      112296  041.050.B
2073      112297  041.050.B
2248      129845  041.050.B
2249      129846  041.050.B
2444      138221  041.050.B
2445      138222  041.050.B
2630      146413  041.050.B
2631      146414  041.050.B
2816      154605  041.050.B
2817      154606  041.050.B
2992      171853  041.050.B
2993      171854  041.050.B
3188      180229  041.050.B
3189      180230  041.050.B
3374      188421  041.050.B
3375      188422  041.050.B
3560      196613  041.050.B
3561      196614  041.050.B
3736      213861  041.050.B
3737      213862  041.050.B
3932      222237  041.050.B
3933      222238  041.050.B
4118      230429  041.050.B
4119      230430  041.050.B
4304      238621  041.050.B
4305      238622  041.050.B






041.050.A
      Unnamed: 0    Dev_Ref
18          1527  041.050.A
19          1528  041.050.A
210         9928  041.050.A
211         9929  041.050.A
396        18289  041.050.A
397        18290  041.050.A
582        26650  041.050.A
583        26651  041.050.A
762        44279  041.050.A
763        44280  041.050.A
954        52680  041.050.A
955        52681  041.050.A
1140       61041  041.050.A
1141       61042  041.050.A
1326       69402  041.050.A
1327       69403  041.050.A
1506       87031  041.050.A
1507       87032  041.050.A
1698       95572  041.050.A
1699       95573  041.050.A
1884      103933  041.050.A
1885      103934  041.050.A
2070      112294  041.050.A
2071      112295  041.050.A
2250      129847  041.050.A
2251      129848  041.050.A
2442      138219  041.050.A
2443      138220  041.050.A
2628      146411  041.050.A
2629      146412  041.050.A
2814      154603  041.050.A
2815      154604  041.050.A
2994      171855  041.050.A
2995      171856  041.050.A
3186      180227  041.050.A
3187      180228  041.050.A
3372      188419  041.050.A
3373      188420  041.050.A
3558      196611  041.050.A
3559      196612  041.050.A
3738      213863  041.050.A
3739      213864  041.050.A
3930      222235  041.050.A
3931      222236  041.050.A
4116      230427  041.050.A
4117      230428  041.050.A
4302      238619  041.050.A
4303      238620  041.050.A






041.050.F
      Unnamed: 0    Dev_Ref
20          1529  041.050.F
21          1530  041.050.F
218         9937  041.050.F
219         9938  041.050.F
404        18298  041.050.F
405        18299  041.050.F
590        26659  041.050.F
591        26660  041.050.F
764        44281  041.050.F
765        44282  041.050.F
962        52689  041.050.F
963        52690  041.050.F
1148       61050  041.050.F
1149       61051  041.050.F
1334       69411  041.050.F
1335       69412  041.050.F
1508       87033  041.050.F
1509       87034  041.050.F
1706       95581  041.050.F
1707       95582  041.050.F
1892      103942  041.050.F
1893      103943  041.050.F
2078      112303  041.050.F
2079      112304  041.050.F
2252      129849  041.050.F
2253      129850  041.050.F
2450      138227  041.050.F
2451      138228  041.050.F
2636      146419  041.050.F
2637      146420  041.050.F
2822      154611  041.050.F
2823      154612  041.050.F
2996      171857  041.050.F
2997      171858  041.050.F
3194      180235  041.050.F
3195      180236  041.050.F
3380      188427  041.050.F
3381      188428  041.050.F
3566      196619  041.050.F
3567      196620  041.050.F
3740      213865  041.050.F
3741      213866  041.050.F
3938      222243  041.050.F
3939      222244  041.050.F
4124      230435  041.050.F
4125      230436  041.050.F
4310      238627  041.050.F
4311      238628  041.050.F






041.050.E
      Unnamed: 0    Dev_Ref
22          1531  041.050.E
23          1532  041.050.E
216         9935  041.050.E
217         9936  041.050.E
402        18296  041.050.E
403        18297  041.050.E
588        26657  041.050.E
589        26658  041.050.E
766        44283  041.050.E
767        44284  041.050.E
960        52687  041.050.E
961        52688  041.050.E
1146       61048  041.050.E
1147       61049  041.050.E
1332       69409  041.050.E
1333       69410  041.050.E
1510       87035  041.050.E
1511       87036  041.050.E
1704       95579  041.050.E
1705       95580  041.050.E
1890      103940  041.050.E
1891      103941  041.050.E
2076      112301  041.050.E
2077      112302  041.050.E
2254      129851  041.050.E
2255      129852  041.050.E
2448      138225  041.050.E
2449      138226  041.050.E
2634      146417  041.050.E
2635      146418  041.050.E
2820      154609  041.050.E
2821      154610  041.050.E
2998      171859  041.050.E
2999      171860  041.050.E
3192      180233  041.050.E
3193      180234  041.050.E
3378      188425  041.050.E
3379      188426  041.050.E
3564      196617  041.050.E
3565      196618  041.050.E
3742      213867  041.050.E
3743      213868  041.050.E
3936      222241  041.050.E
3937      222242  041.050.E
4122      230433  041.050.E
4123      230434  041.050.E
4308      238625  041.050.E
4309      238626  041.050.E






041.138.A
      Unnamed: 0    Dev_Ref
24          1944  041.138.A
25          1945  041.138.A
198         9718  041.138.A
199         9719  041.138.A
384        18079  041.138.A
385        18080  041.138.A
570        26440  041.138.A
571        26441  041.138.A
768        44696  041.138.A
769        44697  041.138.A
942        52470  041.138.A
943        52471  041.138.A
1128       60831  041.138.A
1129       60832  041.138.A
1314       69192  041.138.A
1315       69193  041.138.A
1512       87448  041.138.A
1513       87449  041.138.A
1686       95362  041.138.A
1687       95363  041.138.A
1872      103723  041.138.A
1873      103724  041.138.A
2058      112084  041.138.A
2059      112085  041.138.A
2256      130318  041.138.A
2257      130319  041.138.A
2430      138015  041.138.A
2431      138016  041.138.A
2616      146207  041.138.A
2617      146208  041.138.A
2802      154399  041.138.A
2803      154400  041.138.A
3000      172326  041.138.A
3001      172327  041.138.A
3174      180023  041.138.A
3175      180024  041.138.A
3360      188215  041.138.A
3361      188216  041.138.A
3546      196407  041.138.A
3547      196408  041.138.A
3744      214334  041.138.A
3745      214335  041.138.A
3918      222031  041.138.A
3919      222032  041.138.A
4104      230223  041.138.A
4105      230224  041.138.A
4290      238415  041.138.A
4291      238416  041.138.A






041.138.B
      Unnamed: 0    Dev_Ref
26          1946  041.138.B
27          1947  041.138.B
200         9720  041.138.B
201         9721  041.138.B
386        18081  041.138.B
387        18082  041.138.B
572        26442  041.138.B
573        26443  041.138.B
770        44698  041.138.B
771        44699  041.138.B
944        52472  041.138.B
945        52473  041.138.B
1130       60833  041.138.B
1131       60834  041.138.B
1316       69194  041.138.B
1317       69195  041.138.B
1514       87450  041.138.B
1515       87451  041.138.B
1688       95364  041.138.B
1689       95365  041.138.B
1874      103725  041.138.B
1875      103726  041.138.B
2060      112086  041.138.B
2061      112087  041.138.B
2258      130320  041.138.B
2259      130321  041.138.B
2432      138017  041.138.B
2433      138018  041.138.B
2618      146209  041.138.B
2619      146210  041.138.B
2804      154401  041.138.B
2805      154402  041.138.B
3002      172328  041.138.B
3003      172329  041.138.B
3176      180025  041.138.B
3177      180026  041.138.B
3362      188217  041.138.B
3363      188218  041.138.B
3548      196409  041.138.B
3549      196410  041.138.B
3746      214336  041.138.B
3747      214337  041.138.B
3920      222033  041.138.B
3921      222034  041.138.B
4106      230225  041.138.B
4107      230226  041.138.B
4292      238417  041.138.B
4293      238418  041.138.B






041.138.C
      Unnamed: 0    Dev_Ref
28          1948  041.138.C
29          1949  041.138.C
202         9722  041.138.C
203         9723  041.138.C
388        18083  041.138.C
389        18084  041.138.C
574        26444  041.138.C
575        26445  041.138.C
772        44700  041.138.C
773        44701  041.138.C
946        52474  041.138.C
947        52475  041.138.C
1132       60835  041.138.C
1133       60836  041.138.C
1318       69196  041.138.C
1319       69197  041.138.C
1516       87452  041.138.C
1517       87453  041.138.C

In [ ]:
data1 = pd.read_csv('nba.csv')

In [ ]:
data2 = data1.iloc[:,0:2]
data2

              Name            Team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz
457            NaN             NaN

[458 rows x 2 columns]

In [ ]:
data3 = data1[['Height','Weight']]
data3

    Height  Weight
0      6-2   180.0
1      6-6   235.0
2      6-5   205.0
3      6-5   185.0
4     6-10   231.0
..     ...     ...
453    6-3   203.0
454    6-1   179.0
455    7-3   256.0
456    7-0   231.0
457    NaN     NaN

[458 rows x 2 columns]

In [ ]:
pd.concat([data2,data3],axis = 1)

              Name            Team Height  Weight
0    Avery Bradley  Boston Celtics    6-2   180.0
1      Jae Crowder  Boston Celtics    6-6   235.0
2     John Holland  Boston Celtics    6-5   205.0
3      R.J. Hunter  Boston Celtics    6-5   185.0
4    Jonas Jerebko  Boston Celtics   6-10   231.0
..             ...             ...    ...     ...
453   Shelvin Mack       Utah Jazz    6-3   203.0
454      Raul Neto       Utah Jazz    6-1   179.0
455   Tibor Pleiss       Utah Jazz    7-3   256.0
456    Jeff Withey       Utah Jazz    7-0   231.0
457            NaN             NaN    NaN     NaN

[458 rows x 4 columns]

In [ ]:
data1

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = data1[['Name','Team','Number','Age']]
df

              Name            Team  Number   Age
0    Avery Bradley  Boston Celtics     0.0  25.0
1      Jae Crowder  Boston Celtics    99.0  25.0
2     John Holland  Boston Celtics    30.0  27.0
3      R.J. Hunter  Boston Celtics    28.0  22.0
4    Jonas Jerebko  Boston Celtics     8.0  29.0
..             ...             ...     ...   ...
453   Shelvin Mack       Utah Jazz     8.0  26.0
454      Raul Neto       Utah Jazz    25.0  24.0
455   Tibor Pleiss       Utah Jazz    21.0  26.0
456    Jeff Withey       Utah Jazz    24.0  26.0
457            NaN             NaN     NaN   NaN

[458 rows x 4 columns]

In [ ]:
df1 = data1[['Name','Position','Salary','Age']]
df1

              Name Position     Salary   Age
0    Avery Bradley       PG  7730337.0  25.0
1      Jae Crowder       SF  6796117.0  25.0
2     John Holland       SG        NaN  27.0
3      R.J. Hunter       SG  1148640.0  22.0
4    Jonas Jerebko       PF  5000000.0  29.0
..             ...      ...        ...   ...
453   Shelvin Mack       PG  2433333.0  26.0
454      Raul Neto       PG   900000.0  24.0
455   Tibor Pleiss        C  2900000.0  26.0
456    Jeff Withey        C   947276.0  26.0
457            NaN      NaN        NaN   NaN

[458 rows x 4 columns]

In [ ]:
# Concept of Join using the .merge method
res = pd.merge(df,df1,on = ['Name','Age'])
res

              Name            Team  Number   Age Position     Salary
0    Avery Bradley  Boston Celtics     0.0  25.0       PG  7730337.0
1      Jae Crowder  Boston Celtics    99.0  25.0       SF  6796117.0
2     John Holland  Boston Celtics    30.0  27.0       SG        NaN
3      R.J. Hunter  Boston Celtics    28.0  22.0       SG  1148640.0
4    Jonas Jerebko  Boston Celtics     8.0  29.0       PF  5000000.0
..             ...             ...     ...   ...      ...        ...
453   Shelvin Mack       Utah Jazz     8.0  26.0       PG  2433333.0
454      Raul Neto       Utah Jazz    25.0  24.0       PG   900000.0
455   Tibor Pleiss       Utah Jazz    21.0  26.0        C  2900000.0
456    Jeff Withey       Utah Jazz    24.0  26.0        C   947276.0
457            NaN             NaN     NaN   NaN      NaN        NaN

[458 rows x 6 columns]

In [ ]:
# LEFT
res = pd.merge(df,df1,how = 'left',on = ['Name','Age'])
res

              Name            Team  Number   Age Position     Salary
0    Avery Bradley  Boston Celtics     0.0  25.0       PG  7730337.0
1      Jae Crowder  Boston Celtics    99.0  25.0       SF  6796117.0
2     John Holland  Boston Celtics    30.0  27.0       SG        NaN
3      R.J. Hunter  Boston Celtics    28.0  22.0       SG  1148640.0
4    Jonas Jerebko  Boston Celtics     8.0  29.0       PF  5000000.0
..             ...             ...     ...   ...      ...        ...
453   Shelvin Mack       Utah Jazz     8.0  26.0       PG  2433333.0
454      Raul Neto       Utah Jazz    25.0  24.0       PG   900000.0
455   Tibor Pleiss       Utah Jazz    21.0  26.0        C  2900000.0
456    Jeff Withey       Utah Jazz    24.0  26.0        C   947276.0
457            NaN             NaN     NaN   NaN      NaN        NaN

[458 rows x 6 columns]

In [ ]:
res = pd.merge(df,df1,how = 'right',on = 'Name')
res

              Name            Team  Number  Age_x Position     Salary  Age_y
0    Avery Bradley  Boston Celtics     0.0   25.0       PG  7730337.0   25.0
1      Jae Crowder  Boston Celtics    99.0   25.0       SF  6796117.0   25.0
2     John Holland  Boston Celtics    30.0   27.0       SG        NaN   27.0
3      R.J. Hunter  Boston Celtics    28.0   22.0       SG  1148640.0   22.0
4    Jonas Jerebko  Boston Celtics     8.0   29.0       PF  5000000.0   29.0
..             ...             ...     ...    ...      ...        ...    ...
453   Shelvin Mack       Utah Jazz     8.0   26.0       PG  2433333.0   26.0
454      Raul Neto       Utah Jazz    25.0   24.0       PG   900000.0   24.0
455   Tibor Pleiss       Utah Jazz    21.0   26.0        C  2900000.0   26.0
456    Jeff Withey       Utah Jazz    24.0   26.0        C   947276.0   26.0
457            NaN             NaN     NaN    NaN      NaN        NaN    NaN

[458 rows x 7 columns]

In [ ]:
data1 = {'key':['K0','K1','K2','K3'],
         'Key1':['K0','K1','K0','K1'],
         'Name':['Jai','Piyush','Gaurav','Anuj'],
         'Age':[27,24,22,32],}

data2 = {'key':['K0','K1','K2','K3'],
         'Key1':['K0','K0','K0','K0'],
         'Address':['Nagpur','Kanpur','Allahbad','Kannuaj'],
         'Qualification':['Btech','BA','BCom','B.Hons']}

In [ ]:
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)

In [ ]:
df

  key Key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Piyush   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

In [ ]:
df1

  key Key1   Address Qualification
0  K0   K0    Nagpur         Btech
1  K1   K0    Kanpur            BA
2  K2   K0  Allahbad          BCom
3  K3   K0   Kannuaj        B.Hons

In [ ]:
# LEFT
res = pd.merge(df,df1,how = 'left',on = ['key','Key1'])
res

  key Key1    Name  Age   Address Qualification
0  K0   K0     Jai   27    Nagpur         Btech
1  K1   K1  Piyush   24       NaN           NaN
2  K2   K0  Gaurav   22  Allahbad          BCom
3  K3   K1    Anuj   32       NaN           NaN

In [ ]:
# RIGHT
res = pd.merge(df,df1,how = 'right',on = ['key','Key1'])
res

  key Key1    Name   Age   Address Qualification
0  K0   K0     Jai  27.0    Nagpur         Btech
1  K1   K0     NaN   NaN    Kanpur            BA
2  K2   K0  Gaurav  22.0  Allahbad          BCom
3  K3   K0     NaN   NaN   Kannuaj        B.Hons

In [ ]:
# OUTER
res = pd.merge(df,df1,how = 'outer',on = ['key','Key1'])
res

  key Key1    Name   Age   Address Qualification
0  K0   K0     Jai  27.0    Nagpur         Btech
1  K1   K1  Piyush  24.0       NaN           NaN
2  K2   K0  Gaurav  22.0  Allahbad          BCom
3  K3   K1    Anuj  32.0       NaN           NaN
4  K1   K0     NaN   NaN    Kanpur            BA
5  K3   K0     NaN   NaN   Kannuaj        B.Hons

In [ ]:
# INNER
res = pd.merge(df,df1,how = 'inner',on = ['key','Key1'])
res

  key Key1    Name  Age   Address Qualification
0  K0   K0     Jai   27    Nagpur         Btech
1  K2   K0  Gaurav   22  Allahbad          BCom

In [ ]:
# Date and Time using Pandas
data = pd.date_range('1/1/2022',periods = 24,freq = 'H')
data

DatetimeIndex(['2022-01-01 00:00:00', '2022-01-01 01:00:00',
               '2022-01-01 02:00:00', '2022-01-01 03:00:00',
               '2022-01-01 04:00:00', '2022-01-01 05:00:00',
               '2022-01-01 06:00:00', '2022-01-01 07:00:00',
               '2022-01-01 08:00:00', '2022-01-01 09:00:00',
               '2022-01-01 10:00:00', '2022-01-01 11:00:00',
               '2022-01-01 12:00:00', '2022-01-01 13:00:00',
               '2022-01-01 14:00:00', '2022-01-01 15:00:00',
               '2022-01-01 16:00:00', '2022-01-01 17:00:00',
               '2022-01-01 18:00:00', '2022-01-01 19:00:00',
               '2022-01-01 20:00:00', '2022-01-01 21:00:00',
               '2022-01-01 22:00:00', '2022-01-01 23:00:00'],
              dtype='datetime64[ns]', freq='H')

In [ ]:
rng = pd.DataFrame()
rng['Date'] = pd.date_range('1/1/2022',periods = 72,freq = 'H')
rng

                  Date
0  2022-01-01 00:00:00
1  2022-01-01 01:00:00
2  2022-01-01 02:00:00
3  2022-01-01 03:00:00
4  2022-01-01 04:00:00
..                 ...
67 2022-01-03 19:00:00
68 2022-01-03 20:00:00
69 2022-01-03 21:00:00
70 2022-01-03 22:00:00
71 2022-01-03 23:00:00

[72 rows x 1 columns]

In [ ]:
rng['year'] = rng['Date'].dt.year
rng['month'] = rng['Date'].dt.month
rng['day'] = rng['Date'].dt.day
rng['hour'] = rng['Date'].dt.hour
rng['minute'] = rng['Date'].dt.minute
rng.head(10)

                 Date  year  month  day  hour  minute
0 2022-01-01 00:00:00  2022      1    1     0       0
1 2022-01-01 01:00:00  2022      1    1     1       0
2 2022-01-01 02:00:00  2022      1    1     2       0
3 2022-01-01 03:00:00  2022      1    1     3       0
4 2022-01-01 04:00:00  2022      1    1     4       0
5 2022-01-01 05:00:00  2022      1    1     5       0
6 2022-01-01 06:00:00  2022      1    1     6       0
7 2022-01-01 07:00:00  2022      1    1     7       0
8 2022-01-01 08:00:00  2022      1    1     8       0
9 2022-01-01 09:00:00  2022      1    1     9       0

In [ ]:
url = 'https://bit.ly/uforeports'

df = pd.read_csv(url)

df.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
# Convert the Time Column to Datetime Format
df['Time'] = pd.to_datetime(df.Time) #****
df.head()

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,1930-06-01 22:00:00
1,Willingboro,NaN,OTHER,NJ,1930-06-30 20:00:00
2,Holyoke,NaN,OVAL,CO,1931-02-15 14:00:00
3,Abilene,NaN,DISK,KS,1931-06-01 13:00:00
4,New York Worlds Fair,NaN,LIGHT,NY,1933-04-18 19:00:00

In [ ]:
df.Time.dt.hour.head()
df['hour'] = df['Time'].dt.hour
df.groupby('hour').get_group(22)

,City,Colors Reported,Shape Reported,State,Time,hour
0,Ithaca,NaN,TRIANGLE,NY,1930-06-01 22:00:00,22
17,Hapeville,NaN,NaN,GA,1942-06-01 22:30:00,22
50,Syracuse,NaN,DISK,NY,1947-02-20 22:15:00,22
83,Raton,NaN,OVAL,NM,1947-07-20 22:00:00,22
84,Modesto,BLUE,DISK,CA,1947-08-08 22:00:00,22
...,...,...,...,...,...,...
18203,Saco,NaN,TRIANGLE,ME,2000-12-27 22:10:00,22
18223,Greenville,NaN,NaN,SC,2000-12-29 22:00:00,22
18226,San Francisco,NaN,FORMATION,CA,2000-12-30 22:00:00,22
18227,San Francisco,NaN,TRIANGLE,CA,2000-12-30 22:00:00,22
18234,Capitola,NaN,TRIANGLE,CA,2000-12-31 22:00:00,22

In [ ]:
data1

{'Age': [27, 24, 22, 32],
 'Key1': ['K0', 'K1', 'K0', 'K1'],
 'Name': ['Jai', 'Piyush', 'Gaurav', 'Anuj'],
 'key': ['K0', 'K1', 'K2', 'K3']}

In [ ]:
data3 = pd.read_csv('nba.csv')

In [ ]:
data3['Name'] = data3['Name'].str.upper()
data3['Team'] = data3['Team'].str.upper()
data3['College'] = data3['College'].str.upper()
data3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,AVERY BRADLEY,BOSTON CELTICS,0.0,PG,25.0,6-2,180.0,TEXAS,7730337.0
1,JAE CROWDER,BOSTON CELTICS,99.0,SF,25.0,6-6,235.0,MARQUETTE,6796117.0
2,JOHN HOLLAND,BOSTON CELTICS,30.0,SG,27.0,6-5,205.0,BOSTON UNIVERSITY,NaN
3,R.J. HUNTER,BOSTON CELTICS,28.0,SG,22.0,6-5,185.0,GEORGIA STATE,1148640.0
4,JONAS JEREBKO,BOSTON CELTICS,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,SHELVIN MACK,UTAH JAZZ,8.0,PG,26.0,6-3,203.0,BUTLER,2433333.0
454,RAUL NETO,UTAH JAZZ,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,TIBOR PLEISS,UTAH JAZZ,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,JEFF WITHEY,UTAH JAZZ,24.0,C,26.0,7-0,231.0,KANSAS,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data = pd.read_csv('sgdata.xls')
data.head(4)

,Unnamed: 0,wafer_id,erf_num,Wafer_Map_Name,Mask,Extraction_Id,Extraction_Inst_ID,Test_Inst_ID,Tr_Ref,Test_Date,Test_Type,x_test,y_test,Test_Comments,Dev_Ref,Test_Name,Comments,Sweep_Number,Param,Value
0,1666,43412,6275,0670-00_standard,0670-00,857842475,7689,12253,6531,2022-03-10 09:16:58,Resistor,-5500000,86250000,PCM Reliability Session 2_TST004_A37AC,013.094.G,Resistor,Dev_RES_24_3,1,resistance,3.043346e+04
1,1667,43412,6275,0670-00_standard,0670-00,857842476,7689,12253,6531,2022-03-10 09:16:58,Resistor,-5500000,86250000,PCM Reliability Session 2_TST004_A37AC,013.094.G,Resistor,Dev_RES_24_3,1,r_sq,9.998859e-01
2,1668,43412,6275,0670-00_standard,0670-00,857842468,7689,12253,6531,2022-03-10 09:16:58,Resistor,-5500000,86250000,PCM Reliability Session 2_TST004_A37AC,013.094.C,Resistor,Dev_RES_2_120,1,resistance,1.539377e+07
3,1669,43412,6275,0670-00_standard,0670-00,857842469,7689,12253,6531,2022-03-10 09:16:58,Resistor,-5500000,86250000,PCM Reliability Session 2_TST004_A37AC,013.094.C,Resistor,Dev_RES_2_120,1,r_sq,9.999999e-01

In [ ]:
data['Comments'].str.split('_',expand = True)

       0    1   2    3
0    Dev  RES  24    3
1    Dev  RES  24    3
2    Dev  RES   2  120
3    Dev  RES   2  120
4    Dev  RES   2   24
..   ...  ...  ..  ...
367  Dev  RES   8   12
368  Dev  RES  75    3
369  Dev  RES  75    3
370  Dev  RES  24    3
371  Dev  RES  24    3

[372 rows x 4 columns]